### ISSUE TITLE
Could this design be modified to allow swapable switches?

### ISSUE THREAD

**Issue by dmgm** [mattdibi/redox-keyboard#1]
I have another keyboard (an Input Club K-Type) which allows you to replace switches. As a result I have a couple of sets of plate mounted rather than pcb mount switches. I'd like to try making my own keyboard, but this feature is missing from all current kit designs. I note the Ergodox EZ has this feature.

https://ergodox-ez.com/pages/change-it-yourself

**Comment by mattdibi** [comment]
Hi,
it is possible. The current switch footprints must be replaced with a footprint that supports Kailh PCB sockets and is dual-sided. Save for mechanical interferences it might work.
I could consider it for a future revision.

**Comment by tstumm** [comment]
Is there any update on this? Especially if it is possible to use the Kailh sockets with the cases from Falbatech!

**Comment by mattdibi** [comment]
No update. The current PCB revision doesn't support Kalih sockets.
