### ISSUE TITLE
RGB Underglow Problems

### ISSUE THREAD

**Issue by manno** [mattdibi/redox-keyboard#10]
I'm trying to get RGB underglow to work, but when I follow the instructions it only works on master.
If I recompile and re-wire the strip connections can switch master to the other hand, though.

If I had to guess, I'd say it's either the firmware or the TRRS connection?

**Comment by mattdibi** [comment]
I'm sorry: by 

>  it only works on master.

do you mean that only master hand lights up?

**Comment by manno** [comment]
Yes, I can control animations etc on master.

**Comment by mattdibi** [comment]
The keys on the slave half are working?

**Comment by manno** [comment]
Oh yes, the keys are working.

**Comment by mattdibi** [comment]
Did you set the communication to serial as per [this](https://github.com/mattdibi/redox-keyboard/tree/master/redox#rgb-underglow-firmware) instructions?

**Comment by manno** [comment]
Yes, https://gist.github.com/manno/07faacd854cf74a3468fa45f63fffb7b

**Comment by manno** [comment]
Haha, I thought there were three 😢 
Thanks, will try to get some solder in..

**Comment by manno** [comment]
Managed to solder the missing pin. However on one jack the two ring pads seem to be connected. I already soldered the switches and can't reach those. Maybe I fix that once I have access to a desoldering gun...

Thanks for the help and all the work going into Redox 👍

**Comment by mattdibi** [comment]
I'm glad I was able to help!
