### ISSUE TITLE
YJ-14015 desoldering

### ISSUE THREAD

**Issue by hsgrott** [mattdibi/redox-keyboard#110]
Hi,

I’m sorry for asking this here (it’s not an issue), but is there any advice on how to desolder the YJ-14015?

Thanks in advance and sorry for the inconvenience.

**Comment by mattdibi** [comment]
Hi,

unfortunately no, I don't have any advice for this.

In the past I used a solder wick to separate two shorted pins, but I never tried to desolder the entire MCU.

**Comment by Pastitas** [comment]
I have de-soldered this modules in the past with a hot air station. My advice is, if you plan on reusing it, use aluminium tape to cover things up and be veeeeeeery careful, i couldn't save the one I desoldered. Good luck!
