### ISSUE TITLE
Bootloader/reset mode not accessible anymore

### ISSUE THREAD

**Issue by bilange** [mattdibi/redox-keyboard#115]
I am now apparently unable to boot into bootloader/reset mode. After an unsuccessful flash (more on this later), pressing the reset button on the PCB will make Windows say it's an unrecognized device. The keyboard will switch immediatly (without waiting ~10s in bootloader mode) into normal mode. 

However on Linux (Fedora) I noticed that the device will outright disappear from the lsusb device listing, and stay absent, once I press reset. A power cycle is needed to return to normal mode. 

Normal mode:
```
❯ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 04ca:2006 Lite-On Technology Corp. Broadcom BCM43142A0 Bluetooth Device
Bus 001 Device 002: ID 04f2:b483 Chicony Electronics Co., Ltd USB2.0 VGA UVC WebCam
Bus 001 Device 009: ID feed:0000 Falbatech The Redox Keyboard
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Once I pressed reset (either physically or via QMK RESET): 
```
❯ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 04ca:2006 Lite-On Technology Corp. Broadcom BCM43142A0 Bluetooth Device
Bus 001 Device 002: ID 04f2:b483 Chicony Electronics Co., Ltd USB2.0 VGA UVC WebCam
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

## Unsuccessful flash (root cause)

The situation avove may be my own fault, as this happened right after a flash that apparently stopped mid flashing, and for both sides individually, at 88% for many minutes. Ctrl-C didnt abort, I had to physically unplug the keyboard to halt the procedure (I DO know about not doing it in normal circumstances, but as it appeared obvious flashing was somehow halted mid procedure, what else could I do?).

Console output (from Windows QMK MSYS): 

```
[bilange@warbird qmk_firmware]$ avrdude -p atmega32u4 -P COM3 -c avr109 -U flash:w:stable\ -\ backup_flash.hex

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude.exe: Device signature = 0x1e9587 (probably m32u4)
avrdude.exe: NOTE: "flash" memory has been specified, an erase cycle will be performed
             To disable this feature, specify the -D option.
avrdude.exe: erasing chip
avrdude.exe: reading input file "stable - backup_flash.hex"
avrdude.exe: input file stable - backup_flash.hex auto detected as Intel Hex
avrdude.exe: writing flash (32730 bytes):

Writing | #####                                              | 10% 0.28s
(...)
(skipping many lines)
(...)
Writing | ############################################       | 88% 2.45s
(stuck indefinitely there)
```

While flashing seems to work at first sight (the "stable - backup_flash.hex" file was succesfully applied as my keyboard seems to act as per this file*), it has the side effect of having somehow wiped (partially??) bootloader.

* : With the caveat that this file was the result of backuping a known good config file from the keyboard, per `avrdude -P COM5 -c avr109 -p atmega32u4 -U flash:r:backup_flash.hex:i`. I *do* usually `qmk flash` but have lost my stable .hex binary inbetween workstation reinstallation.

So, is there a way to get out of this situation? Mind you, I CAN use the keyboard, only NOT flash it anymore- so i'm basically stuck with whatever is on my keyboards memory right now.

Thanks!

**Comment by mattdibi** [comment]
Hi,

I'm sorry but I can't help you here. I would redirect you over the QMK github repo for this kind of issues.

Cheers,
Matt

**Comment by bilange** [comment]
Hi Matt, 

It definitely looks like I need to reflash my bootloader according to other people having the same issue with other keyboards. I'm in the process of acquiring the proper wiring tools and an additional Pro Micro and will definitely try to flash it back. 

I understand this is somewhat unrelated for your Github project, but for the sake of your issues section completeness (for future redox readers that could stumble on the same issue), I will report back when my wiring+Pro Micro order is shipped, if you don't mind.

Sources (partial): 

- https://beta.docs.qmk.fm/using-qmk/guides/keyboard-building/isp_flashing_guide
- https://old.reddit.com/r/olkb/comments/prb7wp/keyboard_wont_flash_after_bad_hex_flash/

Thanks!

(Sidenote: I hope submitting my comment won't reopen automatically this issue.)

**Comment by bilange** [comment]
# Guide - Flashing Pros Micros Bootloader

**EDIT 2025-03-29**: I have re-read this guide several years later and though I wasn't clear, so I reworded parts of it and added other online resources to further help. On a personal note, I am swapping Pro Micros on my Redox build as I have now randomly missing keystrokes, so I thought I'd clarify this long comment (and I'm using my own work, years later, to swap Pro Micros. Thanks, past me!!).

While this situation falls outside of Matt's Redox project scope, I thought i'd leave a mini tutorial to get potentials users out of this situation.

The root of the issue is that I flashed a bad firmware to the keyboard's Pro Micro-- in other words, I corrupted the bootloader. I initially messed up by flashing with a `.hex` file that I got FROM the keyboard by reading it. I had the impression that avrdude was behaving similarly to using Acronis TrueImage/Clonezilla or NANDroid backups where a whole partition image can be backupped on file and then restored. But **TLDR**: do NOT read FROM a Pro Micro and flash that resulting file back onto the pro micros! This breaks things (that I don't know about)!

To get yourself out of this issue, you need to flash a working bootloader on the Pro Micros on your keyboard. This situation requires you to have a **third** Pro Micro (by third, I am also counting those inside the Redox in both sides) to use as a programmer (a device responsible of reprogramming another Pro Micro). This procedure is heavily based on https://docs.qmk.fm/isp_flashing_guide#bootloader-firmware, with comments specific to the Redox keyboard and with additional missing tidbits, aimed for hardware newbies like me. 

Warnings: 

* I don't know soldering or electronics altogether, but this situation __absolutely REQUIRES__ you to solder. I expect that people reading my small "guide" and who bought the fully assembled kit from Falba.Tech will be in the same boat. You will probably need to check soldering tutorials online, and practice soldering on PCB or [on this](https://www.amazon.ca/gp/product/B07KS1RPMP/) as I did. You might need to learn about basics on these topics to reflash your bootloader: breadboards, soldering, using a continuity tester (multimeter), ... one Youtube playlist I found useful to begin learning soldering: https://www.youtube.com/playlist?list=PLCZv3eVnjjDKo0G9AIOA48qtfylxDc9d9
* While this worked ONCE (well, twice, for both sides), I can't/won't guarantee this work on your scenario. As I venture in unknown territories (flashing a bootloader, soldering, ...), I simply hope this mini guide will help another person in the future or point them in the right general direction, but no guarantees. Obviously, being posted on this Redox issue, this is known to work on the (Falbatech's) Redox Keyboard.

## Requirements 
### Hardware
I am Canadian, so Amazon links will be from Amazon Canada (sorry!)

* Another [Pro Micro](https://www.amazon.ca/gp/product/B07WPCLF8Y/) 5v (NOT the 3 volt variant) that will act as an ISP Programmer (Note:  Judging from the [readme file](https://github.com/mattdibi/redox-keyboard/blob/master/redox/README.md#bill-of-materials) in the Redox repo, Green Pro Micros "should" be okay for usage as an ISP flasher, crossing my fingers). (Tip: Pro Micros can be sourced from AliExpress for cheaper than Amazon, if you can wait the shipping times)
* Various electronic prototyping accessories: a breadboard, Dupont wires (aka [Jumper Wires](https://en.wikipedia.org/wiki/Jump_wire)), ...
* A soldering iron and solder that have thin enough tip and wire diameters. [The kit I used](https://www.amazon.ca/gp/product/B085Y328GK/) had a 0.8mm wire and was good enough for this usage. (Don't see this item this as my recommendation, as the provided desolder suction tool in the kit appears as really cheaply made.)
* [IC Clamps](https://www.aliexpress.com/item/32589469448.html) of some sort, to (try to) connect a wire onto soldered Pro Micros- more on these later.

### Software
* [QMK Toolbox](https://github.com/qmk/qmk_toolbox)
* [QMK MSYS](https://msys.qmk.fm/), or at least access to the avrdude command.

## Procedure

### Preparing the ISP Programmer

To be extra clear, here we're preparing a THIRD Pro Micro (counting the Pro Micros on the Redox keyboards as one and two) to serve as a programmer to fix our corrupted Pro Micros inside the Redox keyboard.

While it looks like the [QMK ISP Flashing Guide](https://docs.qmk.fm/isp_flashing_guide#bootloader-firmware) says to use [this image for a Pro Micro based programmer](https://github.com/qmk/qmk_firmware/blob/master/util/pro_micro_ISP_B6_10.hex), it doesn't document clearly how to flash the image and skips directly to wiring. 

To flash the ISP Programmer firmware on your third Pro Micro, you need to press Reset on the Pro Micro (see below), then immediately flash the Pro Micro using one of these methods below. You have roughly 8 seconds to initiate the flashing procedure, just like when you need to press Reset and flash a new configuration nwhile using your keyboard regularly (either by pressing the physical switch on the back of the keyboard or by QMK's RESET command). 

#### Flashing an ISP Programmer on the command line
Launch this command immediately after pressing reset on the Pro Micro: 

    avrdude.exe -p atmega32u4 -c avr109 -U flash:w:"path\to\pro_micro_ISP_B6_10.hex":i -P COM6

The parameter `-P COM6` varies - it's a value you need to figure out by yourself as the COM number varies every time the device is plugged in. This is part of the reason why it is recommended to use QMK Toolbox, because once Windows detects the device, Toolbox displays the COM port in its console (and you don't need to deal with this value if flashing with the Toolbox GUI)

#### Flashing the ISP Programmer in QMK Toolbox (prefered)
Just open the hex file in Toolbox, select the right chipset (atmega32u4 for Pro Micros), press reset on the board and hit the Flash button. (OR, you could check Auto-Flash and it will auto-apply once the Pro Micro is seen by your PC as being booted from the bootloader.

#### Pressing reset on the Pro Micro (natively)

"Pressing Reset" here means shorting the `GND` pin (any `GND` will do) and `RST` pin together.  This is easier said than done when the Pro Micro is not soldered or connected, and that's why I soldered the ISP board first onto the breadboard pins that came with it. Then you only need to use a male to male Dupont cable to short GND, which you soldered, to the `RST` pin directly on the Pro Micro board. 

![Image](https://github.com/user-attachments/assets/f9cb05aa-8fd6-4ef7-8c78-fee23f610e0f)

#### Soldering the ISP Programmer
As far as I know, only those pins are absolutely nessessary to solder to use the 3rd Pro Micro as the ISP programmer: `10`, `14`, `15`, `16`, `GND`, `VCC`. This means you dont need to solder the rest of the pins. However, soldering all pins may come useful later if you want to reuse this device on the breadbord. 


### Wiring the programmer on the Redox Pro Micros

By using a breadboard to sit your programmer in, you can use Dupont ("Jumper") wires to send the signal onto the Redox's Pro Micros. 

![wiring](https://user-images.githubusercontent.com/601256/138609744-0b7d28e6-c63f-442e-b92f-ee0aa0afc690.jpg)

- If you want to keep the soldering to an absolute minimum, you will probably need male to female jumper wires with the IC clamps I linked above. The IC Clamps has one male ending that connects into a female jumper wire (the other part is the actual clamp - more on this later). Using this strategy is WAY more trouble than trying to learn the basics of soldering/unsoldering.
- If you are okay with more soldering, you probably want to use a jumper cable that has one end terminated in male and the other having the actual wire stripped, to be soldered (temporarily) on the Redox Pro Micros.

| ISP Pro Micro Pin | Redox Pro Micro Pin |
| -------- | -------- | 
| GND     | GND     |
| 10     | RST     |
| VCC     | VCC     |
|  |  | 
| 15     | 15     |
| 14     | 14     |
| 16     | 16     |

Notes: 
- Be careful, the Pro Micros changes orientation between both sides! Wiring the programmer to the Redox Pro Micros WILL be physically mirrored between the left and right sides of the keyboard. (see [images](https://github.com/mattdibi/redox-keyboard/tree/master/redox#left-hand-back-side-1) from this GH repository for cues of this)
- Generally, pins marked 15, 14 and 16 on the receiving end for the boards that will be reflashed through the ISP programmer needs to be SCLK, MISO and MOSI respectively. Check the boards schematic to be extra careful; i'm only covering Pro Micro to Pro Micro flashing here.

#### A word on IC Clamps

Using the [IC Clamps](https://www.aliexpress.com/item/32589469448.html) is by far the trickiest part of the procedure if you really want to keep the Pro Micros inside the keyboard in place and soldered as-is. Those clamps has alot of torque when gripping, and will most probably just pop up because of the shape of the solder on the pin, which is basically a triangle shape pointing upwards. I assume clamps will only work in these circumstances: 

* When there is very few solder visible at the base of the pins, and the bare pins without any solder on top is visible unobstucted. Clamps will grab easily on the bare pins; OR 
* Add a drop of solder on top of the pin to make an odd shape so the clamps stops sliding upwards.

![solder closeup](https://user-images.githubusercontent.com/601256/138609776-7e87875c-bb88-4096-95ac-6b42686848ee.jpg)
(this is ugly, but this will do. be careful NOT to add too many, so the back cover can still close the keyboard)

![hook](https://user-images.githubusercontent.com/601256/138609818-bd6242de-4e1a-46b3-b6bf-98a4c762be9d.jpg)
(The hook will retract as it is probably spring-loaded or something. You need to push the rod up so the hook opens up.)

My [MacGyver](https://old.reddit.com/r/techsupportmacgyver/) solution was two fold: add a drop of solder over the pin to make an odd shape more prone to hold the clamp in place (as mentioned above), and tape the clamp wire in place afterwards, so the clamp has less incentive to move at all. You're basically walking on eggs there: be extra careful not to touch the wire once a clamp is in place (seriously, Good Luck!!) but the whole circuit temporarily holds to make the flash.

![macgyver](https://user-images.githubusercontent.com/601256/138609869-4cdc8c36-735c-4fc7-9b80-6a5eeb7c3438.jpg)
(I adhere by the saying "*If this is stupid but it works...*" )

In my case, I needed an extra pair of hands: one to make the initial connection with the clamps (on my clamps, you needed to push into the rod to make the actual clamp pop out, requiring both hands), then somebody else to place the temporary tape to secure the clamp rod while connected to the pin.

Once all 6 connections has been made, I suggest you pull out the multimeter / continuity tester to see if all 6 connections, from both ends (from the ISP Pro Micro to the Redox Pro Micro), is working. 

### Flashing the actual Redox controllers

According to [the guide](https://docs.qmk.fm/isp_flashing_guide#bootloader-firmware), the [Caterina / Pro Micro Bootloader 5v](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/avr/bootloaders/caterina/Caterina-promicro16.hex) is the one I used for the Redox. This is actually verifiable as the Redox [rules.mk](https://github.com/qmk/qmk_firmware/blob/master/keyboards/redox/rules.mk) file shows that as well (`BOOTLOADER = caterina`). Manually combining the bootloader and a regular keyboard firmware works as indicated in [Creating a Production Firmware](https://docs.qmk.fm/isp_flashing_guide#creating-a-production-firmware).

This means that when flashing through the ISP Pro Micro, you'd need to flash AT MINIMUM the [Caterina bootloader](https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/avr/bootloaders/caterina/Caterina-promicro16.hex) to get the Pro Micro back on it's feet. Flashing only the bootloader will revive the Redox Pro Micro so that you can AT LEAST press reset on the Redox board to push a new config through QMK. But, to be on the safer side (especially if you flashed something else that the Redox Pro Micro expected), i'd heavily suggest to do flash a complete image (bootloader + compiled Redox QMK hex image), as indicated in [Creating a Production Firmware](https://docs.qmk.fm/isp_flashing_guide#creating-a-production-firmware) procedure.

Flashing a Production Firmware (flashing through the ISP Pro Micro) requires to plug your USB cable from the PC onto the ISP Pro Micro (==not== on the Redox Pro Micro. Do ==NOT== plug both USB cables while the ISP Pro Micro circuitry is connected to the Redox Pro Micros-- this can causes physical damages!!!). Power will be provided on the Redox Pro Micros via the VCC pin you wired. 

You can flash the redox Pro Micros using the ISP Pro Micros it via this command: 

    avrdude -c avrisp -P COM7 -p atmega32u4 -U flash:w:combined.hex:i

Where: 

* `-c avrisp` is actually different THIS TIME, as you're flashing your keyboard Pro Micros through an ISP intermediary, and not directly wired.
* `-P COM7` is a value you need to look up for; QMK Toolbox will immediately tell you what COM port your ISP Pro Micro is, as soon as you give it power. 
* `combined.hex` is just the name I gave to my file that contains a concatenation of the Caterina Bootloader `.hex` file PLUS a Redox compilation `.hex` file. Some tweaking to the combined file is required (this is not a PURE straightforward "copy 2 files into one single output file" concatenation), do consult QMK [Creating a Production Firmware](https://docs.qmk.fm/isp_flashing_guide#creating-a-production-firmware) section.

**Important**: When you'll back with a working bootloader, do \*\***NOT**\*\* try use this combined image (bootloader + Redox hex) when trying to flash your Redox regularly. If you flash this file directly onto the Redox Pro Micros, avrdude will fail while flashing, and corrupt your bootloader (again! :( ). Meaning you'll have to reflash Caterina using an ISP if you do that.

Flashing should take roughly the same time as a regular firmware flash (~10 seconds??), with the same kind of progress bar you were used to when flashing regularly from avrdude.

While everything is still rigged up for flashing though the ISP, test your setup by doing these steps: 

* Plug the keyboard half to the PC, gently lift the keyboard and try a key to see if it works;
* Try to reset your board to go into bootloader mode. You can press RESET **twice** on the Redox board (I believe the bootloader I had originally requires only a single press of RESET, but the newer Catalina bootloader I flashed requires two presses now??) to go into bootloader mode, and try to send a known working Redox compilede firmware the regular way. Be careful to send a regular keyboard firmware and not your combined bootloader+firmware image above (this will definitely break!). 

You can now repeat the procedure on the second half of the keyboard: 

* Connect the PC with the ISP Pro Micro
* Wire the ISP Pro Micro to the Redox Pro Micro pins (Good luck with the IC Clamps!)
* Flash via the ISP with `avrdude -c avrisp ...` command above
* Connect this Redox half to the PC the regular way and test before unwiring the ISP Flasher: 
	* Type using the regular keys 
	* Test going inot bootloader mode (RESET twice)
	* Actually flashing a normal Redox build

I hope this guide will help somebody in the future. If it actually did, let me know by reacting to this message. Sorry about the length of this reply.

External sources: 
- ISP Flashing Guide - https://docs.qmk.fm/isp_flashing_guide#bootloader-firmware
- Creating a Production Firmware - https://docs.qmk.fm/isp_flashing_guide#creating-a-production-firmware
- Soldering for beginners - https://www.youtube.com/playlist?list=PLCZv3eVnjjDKo0G9AIOA48qtfylxDc9d9
- Caterina Pro Micro Bootloader - https://github.com/sparkfun/Arduino_Boards/blob/master/sparkfun/avr/bootloaders/caterina/Caterina-promicro16.hex
