### ISSUE TITLE
keyboard stops working after some time.

### ISSUE THREAD

**Issue by BartStikkers** [mattdibi/redox-keyboard#123]
See title. Unplugging the USB and plugging in again fixes it, but it happens often enough that the keyboard isn't usable. When it happens seems to have no connection to how long it's been plugged in or when it's last been used. It sometimes happens in the middle of typing.

**Comment by mattdibi** [comment]
What type of Redox are you using? Wired or wireless?

**Comment by BartStikkers** [comment]
Wired, the rev1 with the PCBs from Falba.

**Comment by mattdibi** [comment]
Mh... this is really unexpected.

My first suspect would be hardware:
- Double check all solder joints for any kind of short, especially on MCU pins
- Could be a bad Pro Micro. Try using one half at a time and check whether the issue appears on only one half. This could also pinpoint where the (eventual) short could be

**Comment by BartStikkers** [comment]
That was my first thought as well, but I can't find any shorts. I wouldn't be surprised if there was something wrong with these Arduinos though, they were really cheap. I've reflashed them just to rule out any issues from the first time and the problem hasn't reoccured. The only thing I think I'd changed though is the communication between the halves from serial to i2c, maybe I did something wrong there that caused it? I'll try using it tomorrow, see if the problem reoccurs.

**Comment by BartStikkers** [comment]
Problem appears solved, so I guess I screwed something up when I was messing with the config files. Thanks for thinking along!

**Comment by imalexlab** [comment]
I'm having the same issue, also i2c, do you remember what did you change in the files @BartStikkers ?

**Comment by BartStikkers** [comment]
iirc:  qmk_firmware/keyboards/redox/keymaps/default/config.h I swapped the lines for USE_SERIAL and USE_I2C, commenting one and uncommenting the other.
