### ISSUE TITLE
Plans to release project files?

### ISSUE THREAD

**Issue by husseinalijaafar** [mattdibi/redox-keyboard#131]
Hi

Are there plans to release the project files for the PCB? 
I am trying to create a pick and place file, but I need the project files for that (i.e KiCAD, Horizon EDA etc.)

Thanks

**Comment by Taklop** [comment]
I believe they already exist here: `redox-keyboard/redox/pcb/rev1.0/kicad_files/`

**Comment by husseinalijaafar** [comment]
Thanks. I was looking in `redox-w/rev2.0WHS)/pcb/`.
