### ISSUE TITLE
Battery Drain if soldered poorly

### ISSUE THREAD

**Issue by buddylindsey** [mattdibi/redox-keyboard#132]
I just wanted to note an issue I ran into with the Rev2WHS. Might be worth adding a note to the docs somewhere, or close this and leave it here for if someone searches closed issues like I do.

I think I soldered the battery holder a bit too far back and the Hot Swap piece to far forward so that when I push the batter all the way in on one of my sides it touches the hot swap connector. I think this drained my batter in a matter of a few days because as soon as I swapped out the battery the keyboard worked just fine again.

Just wanted to bring it up as a problem that can happen if you aren't careful.

**Comment by mattdibi** [comment]
Thank you for pointing this out. I would keep this issue here for documentation purposes as you suggested.

**Comment by Zielak** [comment]
Same happened here, but that's how my PCB was printed. One fix is to just place some insulating tape over that hot-swap socket.
