### ISSUE TITLE
Created a new case for the Redox Wireless

### ISSUE THREAD

**Issue by marco-silvestri** [mattdibi/redox-keyboard#133]
Howdy!
I've created a new case for the RedoxW, which accomodates two 18650 rechargable Li-ion cells.
Is available here: [https://github.com/marco-silvestri/redox-big-battery](https://github.com/marco-silvestri/redox-big-battery)

Please include it in the main readme, if you find it of any use.

Cheers, 
Marco

**Comment by mattdibi** [comment]
Nice! Thank you for your contribution. I'll update the docs ASAP :)
