### ISSUE TITLE
[Help] diagnosing location of bad joint

### ISSUE THREAD

**Issue by JamesYeoman** [mattdibi/redox-keyboard#145]
Ok, so I've almost got my keyboard ready for primetime, but the column that contains the `p` key in the default keymap is completely dead. Which pin is that column on?

**Comment by mattdibi** [comment]
Hi there,
please refer to the available schematics:
- [Redox](https://github.com/mattdibi/redox-keyboard/blob/master/redox/pcb/Redox-schematic.pdf)
- [Redox Wireless](https://github.com/mattdibi/redox-keyboard/blob/master/redox-w/rev1.0W/pcb/transmitters-schematic.pdf)
- [Redox Wireless HS](https://github.com/mattdibi/redox-keyboard/blob/master/redox-w/rev2.0WHS/pcb/redox_rev2WHS_transmitters_schematic.pdf)
