### ISSUE TITLE
Two sets of redox_w can be paired with each other

### ISSUE THREAD

**Issue by mffseal** [mattdibi/redox-keyboard#148]
I have made two sets of redox_w. I found that crosstalk will occur when the two sets of redox_w work together. How do I avoid this problem? Do I need to modify the Bluetooth firmware?

**Comment by mffseal** [comment]
I changed channel table value and it works.

**Comment by yejianfengblue** [comment]
Hello. Could you please tell me the new value of the channel table? Can it be any integer less than 255? Or where is the documentation saying that?

**Comment by mffseal** [comment]
> 

https://github.com/mattdibi/redox-w-firmware/issues/27
