### ISSUE TITLE
Redox W 2.0 working intermittently

### ISSUE THREAD

**Issue by ChrisMcD1** [mattdibi/redox-keyboard#150]
Hello,

I've been working on my Redox Wireless 2.0 for the past several months. It's certainly been a journey. I didn't want to make a Github issue if I could avoid it since most of them seem to be solved by somebody coming back and saying that they soldered it correctly.

Today I finally got my first keystrokes out of my redox after swapping out my arduino for a fresh one, but then it randomly stopped working! Since then I have had it successfully run on two machines, but then stop working once I power off the transmitter boards. Since this happened on the second machine, I have been unable to get any keystrokes out of the system. I've tried restarting my computer and even re-flashed the arduino and the 3 YJ-14105's.

The only other sign I have that something is wrong is that the battery life on my coin cell batteries has been surprisingly low. Earlier today a battery that I put in a month ago was practically dead and reading 2.3V. I've checked all of the adjacent pins on the YJ-14015's on the transmitter boards to check for shorts and I didn't find any. I'm thinking that it's possible that the transmitters spent a month constantly on trying to connect to the receiver board and never finding it, so that drained the battery faster than the estimated battery consumption? For the record, I am using the 3D printed case.

Has anyone ever seen behavior similar to this where the transmitters will not reconnect after being power off?

EDIT: I've attached some photos of my boards to see if they can provide any valuable information.
![Left_1](https://user-images.githubusercontent.com/43050579/180337837-f354c25e-3e2d-4164-8a2b-085b786502a7.jpg)
![Left_2](https://user-images.githubusercontent.com/43050579/180337846-85e44b54-4976-48f6-a708-45c5c1cc801b.jpg)
![Left_3](https://user-images.githubusercontent.com/43050579/180337847-5f9478c6-04d8-4e67-83bd-8b1e3c0af15c.jpg)
![Receive_1](https://user-images.githubusercontent.com/43050579/180337849-a2c406b9-9166-402a-95c5-73315f89e406.jpg)
![Receive_2](https://user-images.githubusercontent.com/43050579/180337852-5dd523de-678c-47e1-9378-b70c72508ccc.jpg)
![Right_1](https://user-images.githubusercontent.com/43050579/180337855-fa880261-fe55-45f0-bf9b-c2cd257814f4.jpg)
![Right_2](https://user-images.githubusercontent.com/43050579/180337859-d1b18198-598d-4c81-946e-b5ba49fe2594.jpg)
![Right_3](https://user-images.githubusercontent.com/43050579/180337861-5df82a9c-4307-4e76-b8a9-afae1b4b8b4b.jpg)
![Right_4](https://user-images.githubusercontent.com/43050579/180337864-5e39395b-694f-4c99-8070-97dd0a31a09d.jpg)

**Comment by aweiland** [comment]
I'm having the same issue as well.  It randomly worked once, but it hasn't worked since.
