### ISSUE TITLE
[Question] Is it possible to add encoder(s) to 2.0WHS PCBs?

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [mattdibi/redox-keyboard#152]
If so, any pointers on how I should go about it?

**Comment by mattdibi** [comment]
Possible yes, easy not so much.

You need to add the required footprint in the PCBs add the traces to connect to the encoder to the YJ-14015s. Then there's the hard part: you need to write the required code to read the encoders and find a way to send the data over the Gazel protocol to the YJ-14015 receiver and represent the incoming encoder data in a way that QMK can understand.

**Comment by monkey-w1n5t0n** [comment]
Ah I see, thanks for the pointers! I may take a stab at it in the near future.
