### ISSUE TITLE
diodes were soldered wrong direction 

### ISSUE THREAD

**Issue by UrielParienti** [mattdibi/redox-keyboard#153]
Hi,
i finished the left side (work perfectly)
but I am facing issues with the right side.
I'm assuming that the diodes were soldered wrongly, but before I cut them all out I want to be sure that this is the issue.
all of them are soldered with a little black mark on the right side.
when I started uploading the firmware, it finished successfully but non of the keys were working.
so am I doomed to remove them all?

**Comment by mattdibi** [comment]
Hi there,
if you could upload a picture it would help.


Diodes need to be installed following the symbols that are printed on the PCBs like in the image below:
![](https://legonut.gitbooks.io/zen-keyboard/content/assets/diode_1244.jpg)

Anyway you can also refer to the images in this repo for reference.

![](https://github.com/mattdibi/redox-keyboard/raw/master/img/pcb-assembly1.jpg)
![](https://github.com/mattdibi/redox-keyboard/raw/master/img/pcb-assembly2.jpg)

**Comment by UrielParienti** [comment]
so its definitely the issue 

![WhatsApp Image 2022-08-24 at 12 42 31 PM](https://user-images.githubusercontent.com/54390985/186386728-730836ae-a496-4365-9584-9e4d8cf4c240.jpeg)

ill start cutting them off.
hope I did not damage the controller when I desoldered it.

Thanks a lot
