### ISSUE TITLE
LED of redox-w keyboard receiver does not work

### ISSUE THREAD

**Issue by Sp-Link** [mattdibi/redox-keyboard#157]
Hi @mattdibi 
I made the  redox-w keyboard according to the document, and tested that the keyboard works normally, but the LED indicator of the receiver does not blink.I searched the project file, but I couldn't find the description of LED functions.What is the function of the LED on the receiver? When does the LED  blink? I hope I can find the answer from you.

**Comment by mattdibi** [comment]
Hi @Sp-Link,

the LEDs status is set [here](https://github.com/qmk/qmk_firmware/blob/558ab18611665c3b447c27bac82fac2224eadaef/keyboards/redox_w/keymaps/default/keymap.c#L91). They are activated and set depending on the layer you're currently on. By deafult they're set to off.

More info [here](https://github.com/mattdibi/redox-keyboard/issues/93#issuecomment-808697030).

**Comment by Sp-Link** [comment]
> Hi @Sp-Link,
> 
> the LEDs status is set [here](https://github.com/qmk/qmk_firmware/blob/558ab18611665c3b447c27bac82fac2224eadaef/keyboards/redox_w/keymaps/default/keymap.c#L91). They are activated and set depending on the layer you're currently on. By deafult they're set to off.
> 
> More info [here](https://github.com/mattdibi/redox-keyboard/issues/93#issuecomment-808697030).



> 

Thank you very much for your help. The problem has been solved.This design is very ingenious!
