### ISSUE TITLE
Help - locate which pin corresponds to non-functioning key column

### ISSUE THREAD

**Issue by glostis** [mattdibi/redox-keyboard#162]
Hi,

Many thanks for this wonderful design!

I've bought a Falba wired Redox board (the recent version that comes with hotswap), and after a short while one column of keys (the 5 keys circled in blue in the attached screenshot) has stopped working. All other keys work just fine.
![image](https://user-images.githubusercontent.com/25295717/217772900-af3f4d87-e552-41db-b6ba-3d34ec1b7e54.png)
I suspect this is due to a bad joint or something equivalent on a pin of the microcontroller.
- Being completely new to microelectronics in general, could someone confirm this hypothesis?
- I am trying to figure out which pin it is. According to [the Redox PCB schematic](https://github.com/mattdibi/redox-keyboard/blob/master/redox/pcb/Redox-schematic.pdf), I suspect my disfunctioning column is `col6`, and therefore the bad joint must be on pin 10. Am I right? Or could there be a bad joint elsewhere as well?

Thank you

**Comment by mattdibi** [comment]
Hi,
all your assumptions are correct. If you want to be extra sure you can use a multimeter to check continuity. Hope this helps
