### ISSUE TITLE
Optical Switches?

### ISSUE THREAD

**Issue by ninjrdevelop** [mattdibi/redox-keyboard#165]
Would the Rev 2.0WHS work with Optical switches? E.g: https://www.amazon.com/Gateron-Ks-15-Optical-Mechanical-Switch/dp/B083F44F5R

The listing states

> COMPATIBILITY – Optical Switches are compatible with Optical Keyboards and can be hotswapped without desoldering. They are available in 65 PCS, 90 PCS and 120 PCS making them the ideal fit for 60%, TKL and full size keyboards. Gateron Optical switches are not compatible with regular mechanical keyboards.

But I'm not too sure the difference between optical and normal switches.

**Comment by mattdibi** [comment]
@ninjrdevelop no they won't work.

These switches work on with fundamentally different principle than traditional switches. It requires specific support on the PCB level for this to be used and this is not currently supported for the Redox keyboard.

**Comment by ninjrdevelop** [comment]
Roger, thanks for the clarification.
