### ISSUE TITLE
Missing Detail in Length of Extension for 3d printed case.

### ISSUE THREAD

**Issue by irfn** [mattdibi/redox-keyboard#2]
>> use the diodes legs leftover from previous steps as this will make the controller's USB port much lower, this is needed for the 3D printed case. 

This is mentioned in the readme. Can we make this more specific. I am trying to mod the case and needed this detail.

**Comment by mattdibi** [comment]
Sure. What do you need in detail (measures, more detailed pics, a more detailed description...)?

**Comment by irfn** [comment]
@mattdibi Need more measurements. I could find longer header pins if i know how above the controller needs to sit.

**Comment by mattdibi** [comment]
I clarified the description and added some measurements. Is this enough?

**Comment by irfn** [comment]
@mattdibi this is what i was looking for. You can close the issue. Thanks for your help.

**Comment by mattdibi** [comment]
Great. Good luck with your project! :)
