### ISSUE TITLE
redox-w question: Have you had issues with some columns not registering when key from nearby column is held? 

### ISSUE THREAD

**Issue by ilukinov** [mattdibi/redox-keyboard#22]
Hello, thanks for your project, it helped me a lot with my own custom keyboard.
I'm using wiring similar to yours (you don't use pin 8), 
<img width="321" alt="Screen Shot 2019-04-22 at 00 40 44" src="https://user-images.githubusercontent.com/12907231/56475926-b6ba1b00-6497-11e9-80e7-c101175c48d1.png">
but for some reason I'm having weird issue with neighboring columns.  When I'm holding down key from one column another one(neighboring) won't work. 
For example:
- if I'm holding shift(c0r3) key then none of keys from c1 will work (1 q a z).
- if I'm holding z(c1r3) key then none of keys from c2 work (2 w s x) but c0 keys will work just fine as well as all other keys, so keys from c0, c1, c3, c4, c5, c6 will still work.

Have you had any issues like that? Can you test such scenarios on your keyboard (left part)

Thank you.

**Comment by mattdibi** [comment]
Hi,
I've never came encountered such behavior. Double check your soldering, it looks a hardware problem to me.

**Comment by ilukinov** [comment]
The weird part is that when I'm hooking up same matrix to promicro all works just fine. That's what get's me confused.

**Comment by mattdibi** [comment]
> when I'm hooking up same matrix to promicro all works just fine

...that's weird. Are absolutely sure everything stays the same between switching from the pro micro to the core5122? If it works for the Pro Micro it should work for the Core51822 too...

**Comment by ilukinov** [comment]
Well, since no one has similar issues I'm closing it. Maybe it's just my chip revision or something.
