### ISSUE TITLE
ALPS compatibility

### ISSUE THREAD

**Issue by LinkedList** [mattdibi/redox-keyboard#23]
Hi, I was just wondering if this design would fit ALPS type switches?

I know it says Cherry MX in the README, but the holes look similar to iris and that supposedly supports alps.

**Comment by mattdibi** [comment]
Hi,

the Redox wireless PCB and the Redox wired PCB should both fit ALPS switches.
Unfortunately they're not supported by the current case designs due to the keyswitch holes dimensions. To fit ALPS switches a case redesign is needed.

Hope this helps.

**Comment by LinkedList** [comment]
Thank you very much.
