### ISSUE TITLE
Flat cut case design

### ISSUE THREAD

**Issue by Pastitas** [mattdibi/redox-keyboard#28]
Would it be possible to get the stl from the japanese guy that did the acrylic cut case?

**Comment by mattdibi** [comment]
You should ask him directly, I do not have his files.

You should also note that he used [https://github.com/mattdibi/redox-keyboard/blob/master/redox/case/redox_rev1-brd.dxf](this) as a base... it shouldn't be hard to reproduce for your particular machine.

Hope this helps!

**Comment by mattdibi** [comment]
Closing as resolved.
