### ISSUE TITLE
Wireless range issues

### ISSUE THREAD

**Issue by InvaderSquibs** [mattdibi/redox-keyboard#31]
I have been having issues with only one side of my redox wireless. The right side can go well over a few feet with no missed keys, but the left side has to be within a foot for the receiver to pick it up. I know it may be a shot in the dark but any ideas of what I can try to trouble shoot? (I have already tried mucking about with the batteries and know that isn't the problem)

**Comment by mattdibi** [comment]
Maybe related to [this](https://github.com/mattdibi/redox-w-firmware/issues/3#issue-442735897). Still haven't found the issue.

Are you using the aluminium case?

**Comment by InvaderSquibs** [comment]
I am using a wooden case from falbatech. I ran a few tests with it and have been finding that though the range can go pretty far but struggles with any sort of interfere  between direct line of sight.so even if I waved my hand in front of the sensor it would cut off if the sensor was over a foot away. I rearranged my setup a bit and now it rarely happens

**Comment by mattdibi** [comment]
Thanks for the insight. I'm glad you found a solution.
