### ISSUE TITLE
flashed firmware... now what?

### ISSUE THREAD

**Issue by crafttherapy** [mattdibi/redox-keyboard#32]
So i flashed the firmware to the receiver and both left and right sides. i connect the receiver and turn on the keyboards but nothing works. 

is there a specific sequence i need to follow? are the left and right sides automatically paired to the receiver?

**Comment by mattdibi** [comment]
Did you programmed the Arduino Pro Micro?

**Comment by crafttherapy** [comment]
i did do all that but the keyboard doesn't work. pretty sure everything is soldered correctly and programmed as per the build instructions. did i need to program the Arduino Pro Micro separately from the receiver section?

**Comment by mattdibi** [comment]
Nope. The way the Arduino is programmed doesn't matter.

Did you turn on the two halves of the keyboard? Did you programmed the receiver?

**Comment by crafttherapy** [comment]
got it working... totally didn't flash qmk firmware on the pro micro. everything works now. Thank you for amazing project.

**Comment by mattdibi** [comment]
Glad you fixed it! Enjoy your keyboard :)
