### ISSUE TITLE
Pcb board rotary encoder and keyboard lights

### ISSUE THREAD

**Issue by ArtAdictedArchitect** [mattdibi/redox-keyboard#40]
Is it possible to add Iris style linear rotary encoders to the Redox?

I really want to be able to add the ec11 rotary encoders the Iris keyboard has + backlighting for the keys individually 

>

**Comment by mattdibi** [comment]
This needs modification to the case and pcb (at least for the backlighting). You're welcome to modify the available files, I cannot right now due to lack of free time.

Hope this helps.
