### ISSUE TITLE
Receiver case

### ISSUE THREAD

**Issue by harshitgoel96** [mattdibi/redox-keyboard#41]
Hi,

I am is process of building the redox wireless keyboard. I looked the files available for Redox-w, but could not find a 3d printable case for the receiver. Can you please provide something for receiver?

**Comment by harshitgoel96** [comment]
Punctuation

**Comment by mattdibi** [comment]
I haven't designed any case for the receiver. Feel free to design your own :)

**Comment by harshitgoel96** [comment]
Hi. I found one on thingiverse


https://www.thingiverse.com/thing:2841059

**Comment by mattdibi** [comment]
This one is for the Mitosis receiver. It should work for the Redox too though.
