### ISSUE TITLE
Can i use Atmega328p based pro micro for dongle? 

### ISSUE THREAD

**Issue by harshitgoel96** [mattdibi/redox-keyboard#42]
Hi,

I got fake pro micro delivered which uses atmega328p instead of atmega32u4. Will it be possible to use it with the dongle firmware.?

**Comment by mattdibi** [comment]
Hi,

can you upload a picture of the pro micro?

**Comment by harshitgoel96** [comment]
found correct pro micro laying arround. fake ones does not even have the usb port. so it would have not worked at all.
