### ISSUE TITLE
Buttons don't work or output character many times

### ISSUE THREAD

**Issue by charafau** [mattdibi/redox-keyboard#53]
Hi! I soldered my first redox keyboard with PCBs from falbatech. Unfortunetly I needed to desolder one controller and solder two buttons under it because I forgot to solder them. 

Now one half's buttons don't work or output character many times, even if I only connect one half through mini-usb. Any debugging tips, hints? Should I buy one more pcb, controller and buttons ?

Thanks!

**Comment by mattdibi** [comment]
Hi,

Before ordering new PCBs double check your soldering. Looks like there might be a naughty joint somewhere.

Hope this helps!

**Comment by DickThomas** [comment]
i had a similar issue to this. 

turns out I had a blob of solder on the 5v/3v j1 on the arduino.

I hope this is of help.

**Comment by charafau** [comment]
broken controller, thank you all for help - closing
