### ISSUE TITLE
Redox rev.1 case will fit?

### ISSUE THREAD

**Issue by chrismelba** [mattdibi/redox-keyboard#54]
Hi,

I'm looking to build a 3d printed version of this. Will the wired case fit the wireless version? I assume it'll just have an extra couple of holes for the defunct cables, but want to check that the additional chips won't foul on anything etc.

**Comment by mattdibi** [comment]
Hi,

[here](https://github.com/mattdibi/redox-keyboard/tree/master/redox-w/case) you can find the wireless version of the case.

In any case (pun intended) the wired case should fit the wireless pcbs too.

Hope this helps.

**Comment by chrismelba** [comment]
Thank you :)
