### ISSUE TITLE
three columns can not work

### ISSUE THREAD

**Issue by yoution** [mattdibi/redox-keyboard#56]
I make a redox-wireless keyboard, the  right half  can work well, but in the left half, three columns can not work, others can work,  I don't know how to solve the problem.

the keys  in the  red box , none of them can work
![image](https://user-images.githubusercontent.com/3863914/77849618-a9f18b80-71ff-11ea-81c4-f62f87ca5c2a.png)

this is the back side
![image](https://user-images.githubusercontent.com/3863914/77849628-b5dd4d80-71ff-11ea-99b0-dffe36b27d50.png)

![image](https://user-images.githubusercontent.com/3863914/77849640-c1307900-71ff-11ea-8da8-33c345fbfd63.png)

**Comment by mattdibi** [comment]
Double check soldering.

Usually undetected keypresses on some columns are related to soldering problems. Judging from the YJ-14015 picture it seems a likely cause.

Hope this helps.

**Comment by yoution** [comment]
@mattdibi  thanks，I screw up， the pcb panel was broken by my pincers， I need to remake the pcb， It will take one month maybe， I will try again after  I receive the pcb and  mcu

**Comment by yoution** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/3863914/79635738-4aa2ed80-81a5-11ea-8acc-928258529704.jpeg)

I am very excited it works, thanks you @mattdibi
