### ISSUE TITLE
Sir,Can you tell me how to compile the 51822`s Program of Transmitters?

### ISSUE THREAD

**Issue by latincompass** [mattdibi/redox-keyboard#58]
Sir,Can you tell me how to compile the 51822`s Program of Transmitters?
Just these files

![Latinpad](https://github.com/latincompass/self/blob/master/33333333333333200420111942.png)

**Comment by mattdibi** [comment]
Closed as duplicate of https://github.com/mattdibi/redox-w-firmware/issues/10
