### ISSUE TITLE
What is RedoxRev2.step for?

### ISSUE THREAD

**Issue by truthbeliever** [mattdibi/redox-keyboard#66]
Hello,

recently there has been the RedoxRev2.step added to the repository. 
Now I found some 3D print service who would print that step file. it is even cheaper than the print with the stl files. 
Is the RedoxRev2.step valid for 3Dcase printing? is there a difference to the stl files apart from the file format? Does the step file contain bottom and top part?

Thank you

**Comment by mattdibi** [comment]
Hello,

the step file contains the project files for helping in customization and modification of the keyboard. Please use the STL for printing.
