### ISSUE TITLE
Redox RGB problems

### ISSUE THREAD

**Issue by TheWeirdDodo** [mattdibi/redox-keyboard#72]
Hi there,

So my redox build is starting to work out slowly but i just encountered a new problem when using RGB. I set up my right hand as master and it is connected to the PC. The keyboard works also the RGB works but if i cycle through the different RGB modes and I activate an effect where the color changes, both halfes get stuck and need to be seperated and the reflashed. So far only the static colors work. As information for troubleshooting, I still have both resistors soldered into place, don't know if that may cause the problem and next would be that i had EE_Hands on a test firmware activated and flashed both halves with the corresponding eeprom, since then I erased the eeprom on both halves but I am not sure if i need to run a specific command to get it back to the original state.
I hope you can help me out with this. Thanks in advance.

Edit: It only happens with rainbow type color effects. Meaning if it is a breathing color change effect it will work but if its a rainbow cycle or multiple different colors the keyboard will get stuck.

Edit2: It also happens after like two seconds of being plugged in and if one half gets unplugged it will work again on the master half of the keyboard but if the second half gets plugged back into the master it will get stuck again until the second half is unpluged.

Edit3: It's not happening on all multicolored RGB modes. Very weird problem in my opinion. (sorry for the spam)

Edit4: Problem found: Too many LEDs (42 in total) and had too much current for the arduinos. Fix: lowered the max brightness.

**Comment by mattdibi** [comment]
Glad you found the solution!
