### ISSUE TITLE
Hotswap sockets

### ISSUE THREAD

**Issue by hsgrott** [mattdibi/redox-keyboard#73]
Hi,

There is something I would like to ask: are there any plans to create a PCB design with support to Kailh hotswap sockets? It seems that there is a github repository with the footprints for KiCAD here: [https://github.com/daprice/keyswitches.pretty](https://github.com/daprice/keyswitches.pretty).

By the way, congratulations for the keyboard design, it looks awesome!

Best regards.

**Comment by mattdibi** [comment]
Hi,

thank you.

Unfortunately lately I'm really busy with my job and other project. I don't plan to add this feature in the near future.
