### ISSUE TITLE
LED Support

### ISSUE THREAD

**Issue by Vicepredator11** [mattdibi/redox-keyboard#81]
I was planning to try adding some smd leds, on the PCB, to light transparent switches, but i don't know how to interface them with QMK and how to wire them up. I'm looking for some effects like Razer keyboards (some effects require a button to led connection) for example the effect where you click on a key and that switch turns on.

can someone help me doing this?

**Comment by mattdibi** [comment]
Refer to the QMK documentation:
- [RGB Lighting](https://beta.docs.qmk.fm/using-qmk/hardware-features/lighting/feature_rgblight)
- [RGB Matrix](https://beta.docs.qmk.fm/using-qmk/hardware-features/lighting/feature_rgb_matrix)
