### ISSUE TITLE
New 3d printed case design

### ISSUE THREAD

**Issue by Pastitas** [mattdibi/redox-keyboard#82]
Hi, i finally uploaded my design for the case, so I wanted to tell you so you can link it
https://github.com/Pastitas/Redox-neodox-Case

**Comment by mattdibi** [comment]
Hi,
this is *awesome*! I'll gladly add a link in the documentation, thank you for letting me know :)

**Comment by Pastitas** [comment]
Thanks! Great keboard btw, i'm loving it a whole lot!
